# Generated by Django 3.0.2 on 2020-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taglist', models.TextField()),
            ],
            options={
                'db_table': 'newcategory',
            },
        ),
    ]
