# Generated by Django 3.0.2 on 2020-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='title',
            field=models.CharField(default='jj', max_length=100),
        ),
    ]
